### ISSUE TITLE
Client Python

### ISSUE THREAD

**Issue by k3rn3lpanicc** [SharifAIChallenge/AIC19-Client-Python#1]
bade run kardane server va etesal client python , ye "preprocess" print mishe badesh error mide .
moshkelesh kojast ?
error : 
`AttributeError: 'World' object has no attribute '_World__game_constants'`
man be source ha dast nazadam sefan hamoonaro test kardam.
[client.log](https://github.com/SharifAIChallenge/AIC19-Client-Python/files/2847704/client.log)

**Comment by mohammadrezza** [comment]
update kon, client et ghadimie

> bade run kardane server va etesal client python , ye "preprocess" print mishe badesh error mide .
> moshkelesh kojast ?
> error :
> `AttributeError: 'World' object has no attribute '_World__game_constants'`
> man be source ha dast nazadam sefan hamoonaro test kardam.
> [client.log](https://github.com/SharifAIChallenge/AIC19-Client-Python/files/2847704/client.log)

**Comment by matinmatinmatin** [comment]
client jadid be ye khat az kode Model.py gir mide mige syntaxesh eshtebahe : 
`if hero_id is not None and ability_name is not None and cell is not None:`
in khatesho mige
vali syntaxesh doroste
chera injoorie?

**Comment by armagg** [comment]
اون مربوط به نسخه قبلی هستش و نسخه ریلیز این مشکل رو نداره
