### ISSUE TITLE
str funct for map is wrong

### ISSUE THREAD

**Issue by thinkingparticle** [SharifAIChallenge/AIC19-Client-Python#10]
https://github.com/SharifAIChallenge/AIC19-Client-Python/blob/3dfad35f8ac45fdd096beb5ca3d6bfadf2a28d4f/Model.py#L205

    def __str__(self):
        string = ''
        for row in self.row_num:
            for col in self.column_num:
                string += str(self.get_cell(row, col))
            string += '\n'

self.column , self.row_num int hast o iteratesh error mide
ehtemalan bayad range(self.row_num) va range(self.column_num) bashe
tahesh ye return string ham mikhad
albate felan info ziadi nemide 😄

**Comment by matinmatinmatin** [comment]
آخرین ورژن کلاینت رو تست کنید
احتمالا کلاینت شما آپدیت نیست

**Comment by armagg** [comment]
مشکل در نسخه های جدید برطرف خواهد شد :)
