### ISSUE TITLE
bug in debug file name when DEBUGGING_MODE=True

### ISSUE THREAD

**Issue by thinkingparticle** [SharifAIChallenge/AIC19-Client-Python#11]
https://github.com/SharifAIChallenge/AIC19-Client-Python/blob/f172f2bd2d092d46e135fdba715259acf531d995/Model.py#L71

OSError: [Errno 22] Invalid argument: 'client- 2019-02-10 17:10:43.034198.log'

windows ":" ro to name e file ejaze nemide. 
intori ok mishe:

```
World.LOG_FILE_POINTER = open('client' + '- ' +
                                          datetime.datetime.now().strftime("%Y-%m-%d %H-%M-%S.%f") + '.log', 'w+')
```

**Comment by armagg** [comment]
ممنون از اطلاع رسانی شما  
این مورد رو درنسخه‌ها‌ی بعدی برطرف میکنیم.
