### ISSUE TITLE
world.get_path_move_directions

### ISSUE THREAD

**Issue by AlirezaKeshavarz83** [SharifAIChallenge/AIC19-Client-Python#12]
تابع چیزی بر نمی گردونه
hero1=world.get_hero(1)
cella=hero1.current_cell
hero2=world.get_hero(2)
cellb=hero2.current_cell
if cella==cellb:
    print("OH!")
l=world.get_path_move_directions((cella.row,cella.column),(cellb.row,cellb.column))
 print(l)

**Comment by armagg** [comment]
تابع 
get_path_move_directions 
 نمیتواند همینطور به ترتیب یک سری ورودی بگیرد. برای ورودی دادن باید از روش زیر استفاده کنید : 
`world.get_path_move_directions(start_cell = cella, end_cell= cellb)`
