### ISSUE TITLE
مشکل enum ها در توابع / python3

### ISSUE THREAD

**Issue by kingk13** [SharifAIChallenge/AIC19-Client-Python#13]
الان برای pick کردن هیرو توی پایتون منطقا باید این کار رو کرد:
game = Model.World()
game.pick_hero(Model.HeroName.SENTRY)

ولی این ارور از کلاینت دریافت میشه:
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/king0k/Documents/AI_Kill_Me_Python/AIC19-Client-Python-master/Network.py", line 68, in run
    self.message_handler(self.receive())
  File "Controller.py", line 72, in handle_message
    threading.Thread(target=self.launch_on_thread(self.client.pick, new_world)).start()
  File "Controller.py", line 84, in launch_on_thread
    action(new_world)
  File "/home/king0k/Documents/AI_Kill_Me_Python/AIC19-Client-Python-master/AI.py", line 11, in pick
    game.pick_hero(Model.HeroName.SENTRY)
  File "/home/king0k/Documents/AI_Kill_Me_Python/AIC19-Client-Python-master/Model.py", line 803, in pick_hero
    self.queue.put(Event('pick', [hero_name.value]))
AttributeError: 'NoneType' object has no attribute 'put'

مگه نباید توی ورودی تابع pick_hero از enum هایی که ساخته شدن استفاده کرد پس چرا ارور میده؟

**Comment by armagg** [comment]
تابع پیک خودش یک ورودی از جنس 
World 
داره که فیلد های اون ست شده اند و لازم نیست یا بهتره بگم نباید خودتون اون رو یک ابجکت جدید ازش بسازید. 
از همان ورودی که به تابع دادیم اگر استفاده کنید مشکل حل میشود

**Comment by kingk13** [comment]
سلام
من این کاری که شما گفتید رو کردم و این شکلی شد:
`world.pick_hero(Model.HeroName.SENTRY)`
ولی وقتی که میخوام لیست هیرو ها رو بگیرم (چه خودی چه دشمن) به من میگه که لیست خالیه:
`print(world.my_heroes)`
Output:
`[]`

**Comment by houshangi** [comment]
manam hamin moshkelo daraam!!!

**Comment by RuhollahSeka** [comment]
شما قهرمان ها رو در همون نوبت که انتخاب می‌کنید، چاپ می‌کنید یا در نوبت بعدش؟ اگر تا ته مراحل انتخاب قهرمانی انتخاب نمی‌شه، لطفا فایل‌های مربوطه کلاینتتون رو برای آدرس زیر ایمیل کنین
r.sekaleshfar@gmail.com

**Comment by kingk13** [comment]
مشکل اینه که قهرمانی که توی اون مرحله که تابع pick اجرا میشه رو نمیتونیم ببنیم و در اجرای بعدی تابع قابل دیدنه واسه همین هم از اونجایی که این تابع چهار بار اجرا میشه و میتونیم سه تا قهرمان اول خودمان و دشمن رو بدست آوریم:
`import Model


class AI:
    def preprocess(self, world):
        print("preprocess")
        self.pick_turn = 0;
        pass

    def pick(self, world):
        print("[%] Pick Phase:")
        world.pick_hero(Model.HeroName.SENTRY)
        if self.pick_turn == 0:
            pass
        else:
            print(world.my_heroes[-1])
        self.pick_turn += 1
        pass

    def move(self, world):
        print("move")
        pass

    def action(self, world):
        print("action")
        pass
`
الان این کد AI.py منه

Output:

`[%] Pick Phase:
[%] Pick Phase:
id:1	 name:SENTRY
[%] Pick Phase:
id:3	 name:SENTRY
[%] Pick Phase:
id:5	 name:SENTRY`

**Comment by RuhollahSeka** [comment]
شما در همون نوبت انتخابتون نمی‌تونید قهرمانی که انتخاب کردید رو ببینید چون پیامتون باید توسط سرور تایید بشه، آیدی به قهرمان نسبت داده بشه و در نوبت بعد برای شما فرستاده بشه
شما بعد از اتمام مراحل انتخاب در تمام مراحل می‌توانید به تمام قهرمان‌هایی که انتخاب کرده‌اید دسترسی داشته باشید
