### ISSUE TITLE
Compiling Error: ImportError: No module named queue

### ISSUE THREAD

**Issue by YasinMahdizadeh** [SharifAIChallenge/AIC19-Client-Python#14]
سلام. وقتتون بخیر.

`Traceback (most recent call last):
  File "Controller.py", line 10, in <module>
    from queue import Queue
ImportError: No module named queue`

این ارور رو وقت کامپایل کردن فایل کنترلر دریافت می‌کنم. مشکل از کجاست؟!

**Comment by sehraramiz** [comment]
باید با پایتون ۳ اجراش کنی

**Comment by YasinMahdizadeh** [comment]
حل شد
خیلی ممنون
