### ISSUE TITLE
world.get_path_move_directions

### ISSUE THREAD

**Issue by AlirezaKeshavarz83** [SharifAIChallenge/AIC19-Client-Python#15]
تو این تابع هیرو های خودی در نظر گرفته نمیشن
و مسیری که پیشنهاد میده ممکنه از هیرو های خودی رد شه

**Comment by armagg** [comment]
در نظر گرفتن این نکته در این تابع فعلا بر عهده ی شما گذاشته شده اما ممکن است در ریلیز های آتی تابعی برای این کار اضافه کنیم
