### ISSUE TITLE
pick hero

### ISSUE THREAD

**Issue by HSalehpour20** [SharifAIChallenge/AIC19-Client-Python#17]
سلام
من تو گرفتن قهرمانا مشکل دارم، کسی میدونه چطور باید پیک بشن!؟
.
world.pick_hero(Model.HeroName.HEALER)
Model.World.pick_hero(world, hero_name=Model.HeroName.HEALER)
.
در هر صورت my hero خالیه یا چیز نامرتبطی داره

**Comment by sehraramiz** [comment]
مدل اولی که نوشتی درسته
 world.pick_hero(Model.HeroName.HEALER)
برای دسترسی به لیست قهرمانات هم اینو بزن
world.my_heroes

**Comment by HSalehpour20** [comment]
[<Model.Hero object at 0x00000197384ABCC0>,...

چیزی که چاپ میکنه اینه،
get ability هم که میزنم none برمیگردونه
درسته..؟

**Comment by sehraramiz** [comment]
درسته
