### ISSUE TITLE
move function doesnt work !

### ISSUE THREAD

**Issue by houshangi** [SharifAIChallenge/AIC19-Client-Python#18]
i just use a  simple method to move my hero 

world.move_hero(hero_id=heroes[0].id , hero=heroes[0] , direction=Model.Direction.DOWN) 

i even tried it with two argument constructor , but it doesnt move :+1: 

world.move_hero(hero_id=heroes[0].id , direction=Model.Direction.DOWN) 

in return i get : 
None

**Comment by armagg** [comment]
Have you checked the  existence of walls down of your hero ? 
in our default map, we've wall down of your first hero

**Comment by houshangi** [comment]
yes i checked that , is return parameter  'None'  OK ????

**Comment by hamidreza004** [comment]
Yes it's ok :)
world.move is just a function that send a message to server.
