### ISSUE TITLE
get_path_move_directions path heroes problem

### ISSUE THREAD

**Issue by 1-1is0** [SharifAIChallenge/AIC19-Client-Python#19]
![photo_2019-02-12_14-23-05](https://user-images.githubusercontent.com/5065549/52637794-8bd6a800-2ee5-11e9-8fcd-7af8bfbb9545.jpg)

هیرو شماره صفر*

مسیر برگردانده شده از تابع 
get_path_move_directions
هیرو های خودی رو در نظر نمیگیره و باعث میشه هیرو در نقطه گیر کند و قابلیت حرکت نداشته باشد

**Comment by hamidreza004** [comment]
سوال تکراری. 
#15
