### ISSUE TITLE
hero.name returns str instead of HeroName object

### ISSUE THREAD

**Issue by Mr-Alirezaa** [SharifAIChallenge/AIC19-Client-Python#23]
Hi,
in AI module, I write this code: (I pick 4 Sentry heroes in pick phase)
```
def action(self, world: Model.World):
    my_heroes: List[Model.Hero] = world.my_heroes
    hero = my_heroes[0]
        print(hero.name == HeroName.SENTRY)

>>> False
```
this peace of code results in false.
according to the AIC Docs, hero.name must be an instance of HeroName Enum, but it is a string.

another example that shows this issue:
```
print(hero.name)
>>> SENTRY
print(HeroName.SENTRY)
>>> HeroName.SENTRY
```

**Comment by RuhollahSeka** [comment]
The bug is fixed in our latest release. Thanks for reporting.
