### ISSUE TITLE
run python client

### ISSUE THREAD

**Issue by roshan50** [SharifAIChallenge/AIC19-Client-Python#24]
سلام
من نمیدونم چطور باید کلاینت پایتون رو اجرا کنم. از پای چارم که گزینه ران رو میزنم هیچ اتفاقی نمی افته

**Comment by armagg** [comment]
سلام  
یکی اینکه باید در
run > edit configurations 
تیک 
allow running in parallel 
رو بزنید بعد پروژه رو دوبار ران کنید

**Comment by roshan50** [comment]
ممنون 
وقتی etid configurations رو میزنم بجاش debug configuration باز میشه
که همچین گزینه ای نداره

![untitled](https://user-images.githubusercontent.com/18488870/52915121-80b8b900-32e5-11e9-9447-902bc4ed920a.jpg)

**Comment by armagg** [comment]
خب مشکل عجیبیه :) 
به نظرم سعی کنید که کلاینت هارو با دوتا ترمینال مثل همون ترمینال گیتی که باز کردید اجرا بکنی به جای خود پایچرم 

یا مثلا نسخه پایچرم رو عوض کنید چون خیلی مشکل عجیبیه

**Comment by roshan50** [comment]
وقتی کد python3 Controller.py رو تو ترمینال گیت میزنم هیچ اتفاقی نمیفته
البته نمیدونم دقیقا چه اتفاقی باید بیفته چون سرور رو هم که ران میکنم و صفحه وب باز میکنم صفحه زیر میاد
![view html](https://user-images.githubusercontent.com/18488870/52935737-78a55b80-336f-11e9-8d62-d71b8380fd27.jpg)
هر دکمه ای رو هم که بزنم هیچ کاری نمیکنه

**Comment by armagg** [comment]
خب ترمینال ویندوز هم نشد؟! 
اگر میشه به این ای‌دی تلگرام پیام بدین 
@omid0390
