### ISSUE TITLE
Missing functions in Hero class

### ISSUE THREAD

**Issue by Mohre** [SharifAIChallenge/AIC19-Client-Python#25]
Only getAbility() function implemented and other mentioned functions in docs does not implemented.

**Comment by Mr-Alirezaa** [comment]
@Mohre 

> Only getAbility() function implemented and other mentioned functions in docs does not implemented.

Hi
iIt is also mentioned in the AIC docs that in python, all of the attributes are accessible by their name. there is no getter for them.
like this:

```python
hero = Hero(...)
hero.name # instead of hero.get_name()
hero.current_cell # instead of hero.get_current_cell()
hero.current_hp # instead of hero.get_current_hp()
# and so on...
```

This is not only for Hero class, other classes are the same.
