### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by k3rn3lpanicc** [SharifAIChallenge/AIC19-Client-Python#3]
client jadid be ye khat az kode Model.py gir mide mige syntaxesh eshtebahe :
`if hero_id is not None and ability_name is not None and cell is not None:`
in khatesho mige
vali syntaxesh doroste
chera injoorie?

**Comment by k3rn3lpanicc** [comment]
khate ghablish ro injori bayad avaz konid : 
`World.LOG_FILE_POINTER.write('-------cast_ability-------\n' + 'hero_id:' + str(hero_id_) + '\thero:' + str(hero) + '\tability_name:' + str(ability_name) + '\nability:' + str(ability) + '\tcell:' +str(cell) + '\trow:' + str(row) + '\tcolumn:' + str(column))`

**Comment by armagg** [comment]
این مشکل توی کامیت آخر برطرف شده بود ولی ریلیز انجام نداده بودیم 
نسخه ۱.۰۱ ریلیز شد
