### ISSUE TITLE
Client Python : dastresi be tavabe class World va map

### ISSUE THREAD

**Issue by k3rn3lpanicc** [SharifAIChallenge/AIC19-Client-Python#4]

**Comment by k3rn3lpanicc** [comment]
To code python age bezanid World.get_Map kar nemikone chon tarif nashode
age bezanid Map.getCells ham hamintor
bejoz "getcell" va "is_in_map" baghie tavabe tarif nashodan

**Comment by armagg** [comment]
بر اساس اصول کدزنی در پایتون ما از
getter and setter 
استفاده نکردیم و برای دسترسی داشتن به متغیر ها باید فیلد اونهارو فرا بخونید.
  مثلا میتونید  به صورت زیر به نقشه بازی  دسترسی داشته باشید : 
`world.map`
