### ISSUE TITLE
Cannot import Model in AI.py

### ISSUE THREAD

**Issue by alirezaaaaaim** [SharifAIChallenge/AIC19-Client-Python#5]
Salam
tebghe [aks ](https://pasteboard.co/I0m9CqD.png)dar file AI.py ba khataye import movajeham
chi kar bayad bokonam ?

**Comment by armagg** [comment]
چند تا نکته : یکی اینکه پایتون شما ورژن چند است؟‌ما برای اجرا نیاز به پایتون ۳ داریم 
 دوم اینکه چیزی که شما باید اجرا کنید فایل کنترلر هست یعنی باید کد زیر بزنید برای اجرا : 
`python3 Controller.py`
و اینکه لطفا از ریلیز آخر برای کلاینت استفاده کنید.

**Comment by alirezaaaaaim** [comment]
> 
> 
> چند تا نکته : یکی اینکه پایتون شما ورژن چند است؟‌ما برای اجرا نیاز به پایتون ۳ داریم
> دوم اینکه چیزی که شما باید اجرا کنید فایل کنترلر هست یعنی باید کد زیر بزنید برای اجرا :
> `python3 Controller.py`
> و اینکه لطفا از ریلیز آخر برای کلاینت استفاده کنید.

az akharin release estefade kardam va moshkel bartaraf shod
mamnun
