### ISSUE TITLE
trying to connect #1

### ISSUE THREAD

**Issue by HSalehpour20** [SharifAIChallenge/AIC19-Client-Python#7]
file controller.py ro run mikonam vali "trying to connect #1" mimone va nemishe dobare run zad bray client 2
(to cmd mizane "client accepted")

**Comment by k3rn3lpanicc** [comment]
shoma bayad ye copy az pooshe proje begiri kenare khodesh bad control.py avali va dovomi ro run koni
ehtemalan darid ye control.py ro dobar run mikonid ke ghalate

age dorost nashod akharin version server o client ro download konid o dobare test konid

**Comment by armagg** [comment]
باید کلاینت را در دوتا ترمینال مختلف ران کنید و یا اینکه کلا دو کلاینت متفاوت داشته باشید تا کار هر دو به طور جداگانه به سرور وصل بشوند
