### ISSUE TITLE
Hero is not moving 2

### ISSUE THREAD

**Issue by k3rn3lpanicc** [SharifAIChallenge/AIC19-Client-Python#8]
من از الگوریتم خودتون برای مسیریابی استفاده میکنم.
این الگوریتم یکم مشکل داره چون اینو درنظر نگرفته که هیرو های من هم با دیوار هیچ فرقی ندارن و نمیشه ازشون رد شد و چیزی که برمیگردونه با این فرضه که میشه

**Comment by RuhollahSeka** [comment]
توجه کنید که چون قهرمان ها ثابت نمیمونن در نظر گرفتن جای قهرمان ها هم در این متد لزوما کار درستی نیست و به همین دلیل توجه به این نکته به کاربر واگذار شده.
به دلیل درخواست های متعدد به زودی متدی برای اون حالت هم اضافه خواهد شد
