### ISSUE TITLE
log

### ISSUE THREAD

**Issue by HSalehpour20** [SharifAIChallenge/AIC19-Client-Python#9]
چطور میتونیم خروجی بازی رو بدون نمایشگر گرافیکی ببینیم تا یخورده بازی واضح تر بشه برامون؟؟

**Comment by matinmatinmatin** [comment]
با یه حلقه فور تو در تو و
world.map.get_cell(i, j)
وبا خاصیت هایی مثل is_wall

**Comment by AlirezaKeshavarz83** [comment]
میتونی توی هر دست اطلاعات مپ رو بگیری بعد چاپ کنی
